// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

type Env = {
	DIRECT_URL: string;
};

type MyPrismaConfig = {
	schema: string;
	migrations: {
		path: string;
		seed: string;
	};
	datasource: {
		url: string;
	};
};

const config = defineConfig({
	schema: 'prisma/schema.prisma',
	migrations: {
		path: 'prisma/migrations',
		seed: 'tsx ./prisma/seed.ts'
	},
	datasource: {
		url: env<Env>('DIRECT_URL')
	}
} satisfies MyPrismaConfig);

export default config;
